---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products":
    get:
      summary: Retrieve all products
      responses:
        '200':
          description: successful request
    post:
      summary: Create a new Product
      parameters: []
      responses:
        '201':
          description: Product created successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/products/{id}":
    get:
      summary: Retrieve a Product by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Product found
        '404':
          description: Product not found
    patch:
      summary: Partially update a Product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Product updated successfully
        '404':
          description: Product not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    put:
      summary: Fully update a Product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Product fully updated
        '404':
          description: Product not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Delete a Product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Product deleted successfully
        '404':
          description: Product not found
  "/rests":
    get:
      summary: Retrieve all rests
      responses:
        '200':
          description: successful request
    post:
      summary: Create a new Rest
      parameters: []
      responses:
        '201':
          description: Rest created successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/rests/{id}":
    get:
      summary: Retrieve a Rest by ID
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Rest found
        '404':
          description: Rest not found
    patch:
      summary: Partially update a Rest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Rest updated successfully
        '404':
          description: Rest not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    put:
      summary: Fully update a Rest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Rest fully updated
        '404':
          description: Rest not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Delete a Rest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Rest deleted successfully
        '404':
          description: Rest not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
